from .PLOTLY.BAR import BAR
from .PLOTLY.HISTOGRAM import HISTOGRAM
from .PLOTLY.IMAGE import IMAGE
from .PLOTLY.LINE import LINE
from .PLOTLY.SCATTER import SCATTER
from .PLOTLY.SCATTER3D import SCATTER3D
from .PLOTLY.SURFACE3D import SURFACE3D