on:
  push:
    branches:
      - main

name: create-studio-pr

jobs:
  send-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
   
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
        
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Get email
        id: email
        uses: KRANTHI0918/get-github-email-by-username-action@v2.1
        with:
          github-username: ${{ github.actor }}
          token: ${{ steps.generate_token.outputs.token }}
      
      - name: Get last commit message
        run: |
          cd ${{ github.workspace }}
          git fetch origin main
          git checkout main
          echo "LAST_COMMIT_MSG=$(git log -1 --pretty=format:'%s')" >> "$GITHUB_ENV"

      - name: Send pull-request
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          APP_TOKEN: ${{ steps.generate_token.outputs.token }}
          USER_NAME: ${{ github.actor }}
          USER_EMAIL: ${{ steps.email.outputs.email }}
          LAST_COMMIT_MSG: ${{ env.LAST_COMMIT_MSG }}
          COMMIT_SHA: ${{ github.sha }}
          GITHUB_WORKSPACE: ${{github.workspace}}
          STUDIO_PR: true
        run: |
          bash create_pr